# Generated by Django 5.2.7 on 2025-11-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orderitem_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sub_total',
        ),
    ]
